main:
#  图片保存方式: local:本地,oss:阿里云存储
  imgSaveType: local
#  文档保存路径,默认本项目的mds文件夹.不能改
  docPath: mds
#  自动为文件夹和文件添加数字编码
  filePrefix: true
#    打印输出
  needOut: false

#阿里云OSS配置
oss:
  endpoint:
  accessKeyId:
  accessKeySecret:
  bucketName:
  path:
