main:
#  图片保存方式: local:本地,oss:阿里云存储
  imgSaveType: local
#  文档保存路径,默认本项目的mds文件夹.不能改
  docPath: /mds/
#  自动为文件夹和文件添加数字编码,用于排序
  filePrefix: true
#    打印输出
  needOut: false
#  代理地址
  proxy: http://webapi.http.zhimacangku.com/getip?num=1&type=2&pro=&city=0&yys=0&port=1&pack=170903&ts=0&ys=0&cs=0&lb=1&sb=0&pb=45&mr=1&regions=
#阿里云OSS配置
oss:
  endpoint:
  accessKeyId:
  accessKeySecret:
  bucketName:
  path:
  url:
