docList:
  - url: https://doc.iocoder.cn/intro
    savePath: RuoYiVuePro
    enable: true
    cache: false
    name: RuoYiVuePro
    cacheFileName: cache
#    文章主体的class样式
    pageBody: .theme-vdoing-wrapper
#    获取链接的class样式
    sidebar: .sidebar-links
  - url: 888
    savePath: 888
    enable: true
    cache: false
  - url: 999
    name: 999
    savePath: 888
    enable: true
    cache: false