docList:
  - url: https://doc.iocoder.cn/intro
    savePath: RuoYiVuePro
    enable: true
    cache: false
    name: RuoYiVuePro
    cacheFileName: cache
    imgSaveType: local
#    文章主体的class样式
    pageBody: .theme-vdoing-wrapper
#    获取链接的class样式
    sidebar: .sidebar-links
    enableProxy: false
    proxy: http://webapi.http.zhimacangku.com/getip?num=1&type=2&pro=&city=0&yys=0&port=1&pack=170903&ts=0&ys=0&cs=0&lb=1&sb=0&pb=45&mr=1&regions=
  - url: 888
    savePath: 888
    enable: true
    cache: false
  - url: 999
    name: 999
    savePath: 888
    enable: true
    cache: false